### ISSUE TITLE
problem applying theme colors to .Xresources

### ISSUE THREAD

**Issue by Flores02** [budlabs/mondo-contrib#1]
Hello Budrich,

I followed your structure in the xres generator:

I generated mine according to my .Xresources file which by default looks like this:
`#include "/home/dreamer/.urxvtconf"

*.foreground:             #FFFFFF 
*.background:             #3f3f3f

*.cursorColor:            #dedede
*.cursorColor2:           #3f3f3f
*.border:                 #3f3f3f

*.color0:                 #3f3f3f
*.color8:                 #4d4d4d
*.color1:                 #cc9393
*.color9:                 #cc9393
*.color2:                 #7f9f7f
*.color10:                #7f9f7f
*.color3:                 #f0dfaf
*.color11:                #f0dfaf
*.color4:                 #8fbede
*.color12:                #8fbede
*.color5:                 #a7a1e6
*.color13:                #a7a1e6
*.color6:                 #8cd0d3
*.color14:                #8cd0d3
*.color7:                 #dedede
*.color15:                #747875`

So I modified it in my generator (_mondo-template) to make it look like this:
`*.foreground:             %%fg%% 
*.background:             %%bg%%  

*.cursorColor:            %%fg%% 
*.cursorColor2:           %%bg%% 
*.border:                 %%bg%% 

*.color0:                 %%bg%%  
*.color8:                 %%bg2%% 
*.color1:                 %%red%% 
*.color9:                 %%redb%% 
*.color2:                 %%green%%
*.color10:                %%greenb%%
*.color3:                 %%yellow%%
*.color11:                %%yellowb%%
*.color4:                 %%blue%%
*.color12:                %%blueb%%
*.color5:                 %%magenta%%
*.color13:                %%magentab%%
*.color6:                 %%cyan%%
*.color14:                %%cyanb%%
*.color7:                 %%fg%%
*.color15:                %%comment%%
`

Almost the same structure of you, I just deleted some stuff to have a cleaner file. So in my _mondo-apply file the structure is the same as you, so this shouldn't be the problem.

I tried to apply this .Xresources file to my URxvt terminal manually by using 
`xrdb ~/.Xresources` after putting the colors code in the file (hard-way). 

But when I try with `mondo -a zenburn` nothing works, as you can see I also put `#FFFFFF` as my background color in my .Xresources file to see if there would be any changes when I apply the theme but nothing works...

Perhaps I already implemented it with rofi i3 and polybar and it works like a charm. I'm just having this big problem with .Xresources.

Thank you for reading, hope you can give me magic help haha :)
Have a nice day!

**Comment by budRich** [comment]
hmm. It can be tricky to update urxvt, and my setup uses the urxvt reload, perl plugin (which in turn have some dependecies (see the comments for the video about reloading urxvt), so the problem can be related to that, but it can also be something else. It would be easier to figure it out if I could see the actual files (.Xresources, mondo/xres/_mondo-apply and mondo/xres/_mondo-template ), i might be able to find it, but first see if the comments on the video below might not help..

https://youtu.be/37jo_x6bXBk

**Comment by Flores02** [comment]
Mhh, It would be easier if we could talk by mail or discord or maybe a chat platform, can you give me your discord or something else? If you don't want it's ok don't worry, I appreciate your help man!

**Comment by budRich** [comment]
https://gitter.im/budRich-github-io/Lobby

my gitter room, that I haven't visited in a long while, but we can chat there. But i was just about to record a video. start a conversation in the room or start a private conversation. When I reply i am free, but it might take an hour or two before i am done recording.

**Comment by Flores02** [comment]
alright take your time man, I'll ping you on the git room in a private conversation in an hour :)
